package csvparser

import (
	"database/sql"
	"encoding/csv"
	"fmt"
	"strconv"
	"strings"
	"tally/models"
	"tally/queries"
	"time"
)

// specific struct as db type
type transaction struct {
	date        time.Time
	description string
	amount      float64
}

// buildColumnMap converts a BankColumnMap (which maps column names to ColumnTypes)
// into a positional map (which maps column indices to ColumnTypes) by matching
// header names against the bank's configured column names.
// This is necessary because when parsing rows we only have positional indices,
// not column names.
func buildColumnMap(bankColumns models.BankColumnMap, header []string) map[int]models.ColumnType {
	columnMap := make(map[int]models.ColumnType, len(header))
	for idx, name := range header {
		if colType, ok := bankColumns[strings.ToLower(name)]; ok {
			columnMap[idx] = colType
		}
	}
	return columnMap
}

// parseRow parses a single CSV row into a Transaction using the positional
// column map built by buildColumnMap. Returns the parsed transaction, a skip
// bool (true if the row should be skipped e.g. credits), and any parse error.
// ID and PaymentMethodID are not parsed here — ID is auto-generated by the DB
// and PaymentMethodID is set by the caller since it comes from the bank config
// not the CSV row itself.
func parseRow(row []string, columnMap map[int]models.ColumnType) (models.Transaction, bool, error) {
	var entry models.Transaction

	for idx, value := range row {
		switch columnMap[idx] {
		case models.ColumnDate:
			date, err := time.Parse("01/02/2006", value)
			if err != nil {
				return entry, false, fmt.Errorf("invalid date %q: %w", value, err)
			}
			entry.Date = date

		case models.ColumnVendor:
			entry.Vendor = value

		case models.ColumnDescription:
			entry.Description = value

		case models.ColumnCategory:
			entry.Category = value

		case models.ColumnAmount:
			amount, err := strconv.ParseFloat(value, 64)
			if err != nil {
				return entry, false, fmt.Errorf("invalid amount %q: %w", value, err)
			}
			if amount > 0 {
				return entry, true, nil
			}
			entry.Amount = -amount

		case models.ColumnPaymentMethodID:
			id, err := strconv.Atoi(value)
			if err != nil {
				return entry, false, fmt.Errorf("invalid payment_method_id %q: %w", value, err)
			}
			entry.PaymentMethodID = id
		}
	}
	return entry, false, nil
}

// ImportTransactions reads a CSV file and inserts all transactions into the DB
// for a given bank. It fetches the bank's CSV column mapping from the DB so
// that different banks with different CSV formats are handled automatically.
// All inserts are wrapped in a transaction so that if any row fails, the
// entire import is rolled back and no partial data is written.
func ImportTransactions(db *sql.DB, bankName models.BankName, reader *csv.Reader) error {

	header, err := reader.Read()
	if err != nil {
		return fmt.Errorf("empty or unreadable CSV: %w", err)
	}

	bank, err := queries.GetBankByName(db, bankName)
	if err != nil {
		return err
	}

	columnMap, err := queries.GetCSVFormat(db, bank.ID)
	if err != nil {
		return err
	}

	columnIdxMap := buildColumnMap(columnMap, header)

	// batch process all inserts into db
	tx, err := db.Begin()
	if err != nil {
		return fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback()

	stmt, err := tx.Prepare(`
		INSERT INTO transactions (date, vendor, description, category, amount, payment_method_id) 
		VALUES ($1, $2, $3, $4, $5, $6)
	`)
	if err != nil {
		return fmt.Errorf("failed to prepare statement: %w", err)
	}
	defer stmt.Close()

outer:
	for {
		row, err := reader.Read()
		if err != nil {
			break
		}

		entry, skip, err := parseRow(row, columnIdxMap)
		if err != nil {
			return err
		}
		if skip {
			continue outer
		}

		_, err = stmt.Exec(entry.Date, entry.Vendor, entry.Description, entry.Category, entry.Amount, bank.ID)
		if err != nil {
			return fmt.Errorf("failed to insert row: %w", err)
		}
	}

	return tx.Commit()

}
